<?php

$list = ['https://bj.ke.com/xiaoqu/dongcheng/',
        'https://bj.ke.com/xiaoqu/xicheng/',
        'https://bj.ke.com/xiaoqu/chaoyang/',
        'https://bj.ke.com/xiaoqu/haidian/',
        'https://bj.ke.com/xiaoqu/fengtai/',
        'https://bj.ke.com/xiaoqu/shijingshan/',
        'https://bj.ke.com/xiaoqu/tongzhou/',
        'https://bj.ke.com/xiaoqu/changping/',
        'https://bj.ke.com/xiaoqu/daxing/',
        'https://bj.ke.com/xiaoqu/yizhuangkaifaqu/',
        'https://bj.ke.com/xiaoqu/shunyi/',
        'https://bj.ke.com/xiaoqu/fangshan/',
        'https://bj.ke.com/xiaoqu/mentougou/',
        'https://bj.ke.com/xiaoqu/pinggu/',
        'https://bj.ke.com/xiaoqu/huairou/',
        'https://bj.ke.com/xiaoqu/miyun/',
        'https://bj.ke.com/xiaoqu/yanqing/',
        'https://lf.ke.com/xiaoqu/yanjiao/',
        'https://lf.ke.com/xiaoqu/xianghe/',
        'https://lf.ke.com/xiaoqu/guangyang/',
        'https://lf.ke.com/xiaoqu/anci/',
        'https://lf.ke.com/xiaoqu/langfangjingjijishu/',
];